### ISSUE TITLE
Deploying to Heroku with Six Package

### ISSUE THREAD

**Issue by dkbollig** [Parbhat/cookiecutter-django-foundation#5]
When deploying to heroku it is throwing an error that I need to remove six from the requirements files as it is automatically installed. Is there a known workaround for when using this template and deploy to heroku?
![1](https://user-images.githubusercontent.com/2271319/29374844-80c42e58-8278-11e7-868c-3adec8540959.JPG)

**Comment by Parbhat** [comment]
@dkbollig The correct place for this issue is in https://github.com/pydanny/cookiecutter-django have you tried removing the package from requirements file?
