### ISSUE TITLE
libsass dependencies issue with Docker image

### ISSUE THREAD

**Issue by Parbhat** [Parbhat/cookiecutter-django-foundation#6]
Recently cookiecutter-django moved to python:alpine docker image https://github.com/pydanny/cookiecutter-django/pull/1482. It is missing dependencies for libsass used in cookiecutter-django-foundation. Need to add dependencies in this project or send a PR to the main project.

**Comment by builtbyvern** [comment]
is there an easy way to do this manually? just trying to learn this and having the same issues

**Comment by Parbhat** [comment]
Hello @builtbyvern, `python:alpine` is very light and the system packages have to add based on requirements. Like for `cookiecutter-django` required packages are added [here](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L5). `Cookiecutter-django-foundation` uses `django-libsass` so the required packages have to be added to `DockerFile`. So, for learning, you can try to identify those packages by reading the error while building docker image or a quick google search for the packages. Add them locally to check if the build runs.
